### ISSUE TITLE
Broken build - (Inconsistent behaviour)

### ISSUE THREAD

**Issue by PauMAVA** [roy-ganz/toql_mysql_async#1]
Hello!

I am unable to build `toql` because of `mysql_async`. This package uses `mysql_async` version `0.27.1` which does not compile as inside the `Cargo.toml` file from `mysql_async` they import the `mio` crate `0.7.7` without the features `net, os-poll` resulting in the following compile error:

```
error[E0432]: unresolved import `mio::net`
  --> /home/paumava/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.27.1/src/io/mod.rs:14:10
   |
14 | use mio::net::{TcpKeepalive, TcpSocket};
   |          ^^^ could not find `net` in `mio`

error[E0599]: no function or associated item named `new` found for struct `mio::Poll` in the current scope
   --> /home/paumava/.cargo/registry/src/github.com-1ecc6299db9ec823/mysql_async-0.27.1/src/io/mod.rs:360:43
    |
360 |                 let mut poll = mio::Poll::new()?;
    |                                           ^^^ function or associated item not found in `mio::Poll`
```

I would recommend bumping the version of `mysql_async` to `0.29.0` which solves the issue. The problem is that `0.29.0` introduces new breaking changes,  like the removal of the `chrono` module and the privatization of the `BoxFuture` type.

Note: in some cases that I haven't been able to reproduce, the library builds fine, but in most cases, it does not. For example, I have a project that builds just fine in my local machine but fails in the GitHub Actions worker. I have also tried creating a new simple project with the following dependencies:
```toml
toql = "0.4.1"
toql_mysql_async = "0.4.1"
strum = "0.23.0"
strum_macros = "0.23.1"
```
Which does not compile with the aforementioned error.

I haven't been able to reproduce the project that builds successfully.

**Comment by roy-ganz** [comment]
Hi, thanks for your report.
I may have time on Friday morning to look into this otherwise next Monday.

**Comment by roy-ganz** [comment]
Hi, I was able to reproduce the problem.
To fix it, I updated `mysql_async` to `0.29` (as suggested by you) and sorted out the `chrono` issues. 
It would be nice, if you gave it a try before I update `crates.io`:

With these dependencies to Github in `Cargo.toml`
```cargo.toml
toql = { git = "https://github.com/roy-ganz/toql" }
toql_mysql_async = {git = "https://github.com/roy-ganz/toql_mysql_async" }
```
a `cargo update` and `cargo build` should now be successful.
I will then update `crates.io` to the new `0.4.2` version.

**Comment by PauMAVA** [comment]
Hi, thanks for the patch! 😄 

I have verified it and now the compilation succeeds.

**Comment by PauMAVA** [comment]
Hello, will you be able to publish the new version of this crate on crates.io?

Thanks 😄

**Comment by roy-ganz** [comment]
Hi, thanks for the reminder. 
I just updated [toql_mysql_async](https://crates.io/crates/toql_mysql_async) and  [toql](https://crates.io/crates/toql) to version 0.4.2.

I'm closing the issue here. Don't hesitate to open a new one, if thinks don't work as expected.
Have a nice week.
